# Setup oh-my-zsh
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"

# Load the git plugin
plugins=(git)

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Install powerline
. ~/Dotfiles/powerline/powerline/bindings/zsh/powerline.zsh
export VIRTUAL_ENV_DISABLE_PROMPT=true

# Run the common shell commands
source ~/Dotfiles/sh/common.sh
