" Michael Layzell's .vimrc

set nocompatible
filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" Vundle manages itself
Bundle 'gmarik/vundle'

" Syntastic (Syntax checking)
Bundle 'scrooloose/syntastic'
let g:syntastic_error_symbol = '✗'
let g:syntastic_warning_symbol = '⚠'
let g:syntastic_enable_balloons = 1

" Ctrl-P (Fuzzy file search)
Bundle 'kien/ctrlp.vim'
let g:ctrlp_map = '<C-p>'
let g:ctrlp_custom_ignore = '\v\~$|\.(o|swp|pyc|wav|mp3|ogg|blend|exe)$|(^|[/\\])(\.(hg|git|bzr)|node_modules)($|[/\\])|__init__\.py'
let g:ctrlp_switch_buffer = 0
let g:ctrlp_dotfiles = 0

" NerdTree (File Browser)
Bundle 'scrooloose/nerdtree'
nmap <C-o> :NERDTreeToggle<CR>

" Fugitive (Git integration)
Bundle 'tpope/vim-fugitive'
autocmd BufReadPost fugitive://* set bufhidden=delete " Delete fugitive buffers after use

" Latex-Suite (Many functions related to editing latex documents)
Bundle 'git://vim-latex.git.sourceforge.net/gitroot/vim-latex/vim-latex'
set shellslash
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'
let g:Tex_ViewRule_pdf = 'Preview'
imap <C-j> <Plug>IMAP_JumpForward

" Bufkill (Kill buffers without closing the window)
Bundle 'bufkill.vim'

" Supertab (Tab to do autocompletion)
Bundle 'ervandew/supertab.git'

" Surround (More easily control braces surrounding text)
Bundle 'tpope/vim-surround'

" Camel Case Motion (Use w b and e to jump between CamelCase words)
Bundle 'camelcasemotion'
map <silent> w <Plug>CamelCaseMotion_w
map <silent> b <Plug>CamelCaseMotion_b
map <silent> e <Plug>CamelCaseMotion_e
sunmap w
sunmap b
sunmap e

" Coffeescript Integration
Bundle 'kchmck/vim-coffee-script'

" Json Integration
Bundle 'elzr/vim-json'
set conceallevel=0

" Commenting Code
Bundle 'scrooloose/nerdcommenter'
nmap <silent> <C-/> <Plug>NERDCommenterToggle

" Vim Handlebars integration
Bundle 'nono/vim-handlebars'

" Stylus Syntax Highlighting
Bundle 'wavded/vim-stylus'

" Autocompletion for braces
Bundle 'Raimondi/delimitMate'

" LESS CSS support
Bundle 'groenewege/vim-less'

" Solarized Color Scheme
Bundle 'altercation/vim-colors-solarized'

" Jinja2 Syntax
Bundle 'Glench/Vim-Jinja2-Syntax'

" RST Syntax Etc
Bundle 'riv.vim'

" Clojure Crap
Bundle 'tpope/vim-fireplace.git'
Bundle 'tpope/vim-classpath.git'
Bundle 'guns/vim-clojure-static.git'

" Javascript stuff
Bundle 'pangloss/vim-javascript'
Bundle 'mxw/vim-jsx'

" Vimscript powerline replacement thing\
Bundle 'bling/vim-airline'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1

set background=dark
colorscheme solarized
let g:solarized_contrast="high"

" Syntax Highlighting
syntax on
filetype plugin indent on

" Searching
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

" Go to last file <C-e>
nmap <C-e> :b#<CR>
set hidden

" Window Movement options
nmap <C-h> <C-w>h
nmap <C-j> <C-w>j
nmap <C-k> <C-w>k
nmap <C-l> <C-w>l

" Display Line Numbers
set number

" Highlight current line
augroup CursorLine
	au!
	au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
	au WinLeave * setlocal nocursorline
augroup END

" Tab Spacing
source ~/.vim/detect.vim

" Defaults
set ts=4
set sw=4
let g:detectindent_preferred_indent=4

" PYTHON
autocmd FileType python     setl sw=4 sts=4 et | :DetectIndent

" JAVASCRIPT
autocmd FileType javascript setl sw=2 sts=2 et | :DetectIndent
autocmd FileType coffee     setl sw=2 sts=2 et | :DetectIndent
autocmd FileType json       setl sw=4 sts=4 et | :DetectIndent

" HTML-like languages
autocmd FileType html       setl sw=2 sts=2 et | :DetectIndent
autocmd FileType handlebars setl sw=2 sts=2 et | :DetectIndent

" CSS-like languages
autocmd FileType css        setl sw=2 sts=2 et | :DetectIndent
autocmd FileType less       setl sw=2 sts=2 et | :DetectIndent
autocmd FileType scss       setl sw=2 sts=2 et | :DetectIndent


" Make .lessimport files act like less files
autocmd BufNewFile,BufRead *.lessimport set filetype=less
" Make html files handlebars files
autocmd BufNewFile,BufRead *.html set filetype=handlebars

set guifont=Ubuntu\ Mono\ For\ Powerline:h13

" Display the status bar all of the time
set laststatus=2

set encoding=utf-8

